version: '3.8'

services:
  orchestrator:
    build:
      context: .
      dockerfile: docker/Dockerfile_orchestrator
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - PORT=8080
      - HOST=localhost
    volumes:
      - .env:/app/.env
    restart: unless-stopped

  agent:
    build:
      context: .
      dockerfile: docker/Dockerfile_agent
    environment:
      - COMPUTING_POWER=25
      - ORCHESTRATOR_URL=http://localhost:8080
    depends_on:
      - orchestrator


  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/swagger.yaml
      - BASE_URL=/
      - SWAGGER_UI_CORS=true
    volumes:
      - ./swagger.yaml:/swagger.yaml
    depends_on:
      - orchestrator
